alias duschx='du -schx ./* | sort -h'
alias egrep='egrep --color=auto'
alias empty='cat /dev/null > '
alias fgrep='fgrep --color=auto'
alias gitad='git add . --all '
alias gitcm='git commit -m '
alias gitps='git push origin '
alias gitpsm='git push origin master '
alias gitpl='git pull origin '
alias gitplm='git pull origin master '
alias gitck='git checkout '
alias gitckm='git checkout master'
alias gitmg='git merge '
alias gitrm='git rm '
alias gits='git status'
alias gitbsort='git for-each-ref --sort=-committerdate refs/heads/'
alias gitbs=''
alias gitfa='git fetch --all'
alias grep='grep --color=auto'
alias his='history |grep '
alias kil='kill -15 '
alias kil9='kill -9 '
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias psg='ps -ef|grep '
alias subl='/opt/sublime_text/sublime_text . &'
alias tailf='tail -fn 500 '
alias tarzc='tar -pczf '
alias tarzx='tar zxvf '
alias tarzt='tar -ztvf '
alias ubuv='lsb_release -a'
alias psql92='/usr/lib/postgresql/9.2/bin/'
alias unzipl='unzip -l '
alias lport='netstat -lnp | grep '
alias cicon='gnome-desktop-item-edit --create-new ~/Desktop'
alias cddv='cd ~/Development/'
alias cpall='xclip -sel clip < '
alias vup='vagrant up'
alias vhlt='vagrant halt'
alias vsh='vagrant ssh'
alias vspd='vagrant suspend'
alias vsts='vagrant status'
